#!/bin/bash
#SBATCH --job-name=cpi-omp
#SBATCH --account=uzh8
#SBATCH --partition=debug
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --hint=nomultithread
#SBATCH --output=omp-output.log
#SBATCH --error=omp-errors.log
#SBATCH --uenv=prgenv-gnu/26.3:v1
#SBATCH --view=default
#SBATCH --open-mode=truncate
set -e

export OMP_NUM_THREADS=128
echo "Normal CPU binding"
srun ./cpi_omp
echo "CPU binding disabled"
srun --cpu-bind=none ./cpi_omp
